services:
  wwebjs-bot:
    build: .
    container_name: wwebjs-bot
    ports:
      - "3323:3323"
    environment:
      - PORT=3323
    volumes:
      - ./uploads:/app/uploads
      - ./.wwebjs_auth:/app/.wwebjs_auth
      - ./.wwebjs_cache:/app/.wwebjs_cache
      - ./sessions:/app/sessions

    restart: unless-stopped
